### ISSUE TITLE
Get commit list for template

### ISSUE THREAD

**Issue by dbendy** [drone-plugins/drone-email#10]
I would like to get the full list of commits since the last successful drone build for the email template.  I plan to grab all of the messages for these commits and display them in a list in the email body.  Is there a way to access all of these commits while rendering the template with handlebars?

**Comment by tboerger** [comment]
As far as I know that is not directly possible. That gets pretty difficult because we have to query the API to gather this information.

@bradrydzewski maybe you've got an idea for that?

**Comment by dbendy** [comment]
Thanks @tboerger.  In general, is there a way to define a variable in the `.drone.yml` file and then access it within the email template?  Or even to set a variable within the environment and access it within the template?  That would help me here.

**Comment by tboerger** [comment]
@dbendy the available variables are fixed defined, so no way to inject additional variables.

**Comment by dbendy** [comment]
@tboerger: thanks

**Comment by bradrydzewski** [comment]
yep, this would require a custom plugin that queries the Drone API to fetch this information at runtime. It is certainly possible. See the [downstream](https://github.com/drone-plugins/drone-downstream) plugin for an example
